### ISSUE TITLE
How to rank in Figure 5 of your JCIM paper

### ISSUE THREAD

**Issue by pykao** [seokhokang/reaction_condition_vae#1]
Hi Kang,

I think your RactionVAE uses T noises to generate T reaction conditions given reactions and product combination. How can you find the Top-5 Predicted Reactions Conditions for the Figure 5?

Best,
Po-Yu Kao

**Comment by seokhokang** [comment]
The generated reaction conditions are ranked according to their probability scores, assuming the generative distribution follows a Bernoull distribution. For example, consider a model output [0.6, 0.1, 0.3, 0.1, 0.7]. The first and fifth reaction elements form a reaction condition and its probability score is calculated as 0.6 * (1-0.1) * (1-0.3) * (1-0.1) * 0.7.

**Comment by pykao** [comment]
Thank you for your clarification!
